[package]
name = "wait_for_episode"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.13"
teloxide = "0.12"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"